version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:./drizzle/data.db
    volumes:
      - ./frontend/drizzle:/app/drizzle
